<<<<<<< HEAD
# Generated by Django 5.1 on 2024-12-02 09:31
=======
# Generated by Django 5.1.3 on 2024-12-02 09:27
>>>>>>> fb40edc550c8290c00d5a684f5e0cec0ed33b6e2

from django.db import migrations


class Migration(migrations.Migration):
<<<<<<< HEAD
    dependencies = [
        ("booking", "0001_initial"),
=======

    dependencies = [
        ('booking', '0001_initial'),
>>>>>>> fb40edc550c8290c00d5a684f5e0cec0ed33b6e2
    ]

    operations = [
        migrations.RemoveField(
<<<<<<< HEAD
            model_name="subcategory",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Subcategory",
=======
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Subcategory',
>>>>>>> fb40edc550c8290c00d5a684f5e0cec0ed33b6e2
        ),
    ]
